model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 1
  img_size: [512, 512]
  dropout_rate: 0.01
  conv_block: true
  res_block: true 
  feature_size: 32 
  hidden_size: 256 
  mlp_dim: 1024
  num_heads: 8
  qkv_bias: true
  save_attn: true 
  proj_type: "conv"         
  norm_name: "instance"
data:
  low_dose_folder: '/data/coding/Preprocessed_512x512/512/Quarter Dose/1mm/Sharp Kernel (D45)'
  high_dose_folder: '/data/coding/Preprocessed_512x512/512/Full Dose/1mm/Sharp Kernel (D45)'
  csv: '/data/coding/1mmSHARP.csv'
training:
  seed: 42
  batch_size: 64
  lr: 0.0001  # 学习率是训练参数，放在这里更合适
  
  # 学习率调度器是训练过程的一部分，将其嵌套在training模块下
  lr_scheduler:
    name: ReduceLROnPlateau  # 建议明确写出调度器名称
    params:
      mode: 'min'
      factor: 0.1
      patience: 10
      verbose: True
      min_lr: 0.000001 # 1e-6
