data:
  low_dose_folder: '/data/coding/Preprocessed_512x512/512/Quarter Dose/1mm/Sharp Kernel (D45)'
  high_dose_folder: '/data/coding/Preprocessed_512x512/512/Full Dose/1mm/Sharp Kernel (D45)'
  csv: '/data/coding/1mmSHARP.csv'
  
model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 1
  channels: [32, 64, 128, 256]
  strides: [2, 2, 2]  # channels有4个值，对应3次下采样，所以strides长度为3是正确的
  dropout: 0.01
  kernel_size: 3
  up_kernel_size: 3
training:
  seed: 42
  lr: 0.0001  # 学习率是训练参数，放在这里更合适
  
  # 学习率调度器是训练过程的一部分，将其嵌套在training模块下
  lr_scheduler:
    name: ReduceLROnPlateau  # 建议明确写出调度器名称
    params:
      mode: 'min'
      factor: 0.1
      patience: 10
      verbose: True
      min_lr: 0.000001 # 1e-6
  
